version: "3"
services:
  #first time setting up project
  first:
    container_name: first_beckend
    image: node:20-alpine
    command: sh -c "npm i -g @nestjs/cli && nest new app -g -p npm"
    volumes:
      - ".:/app"
    restart: unless-stopped