version: "3"
services:
  chat:
    container_name: chat
    env_file: 
      - .env
      - .env.chat-db
    build:
      context: .
      dockerfile: Dockerfile
    image: chat
    volumes:
      - ".:/app" #only for developement
      - "/app/node_modules"
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "3001:3000" #only for testing porposes
    depends_on:
      - postgres
  
  chat_db:
    container_name: chat_db
    env_file: 
      - ../../backend/chat/.env
      - ../../backend/chat/.env.chat-db
    build:
      context: ../../database/chat_db
      dockerfile: Dockerfile
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432" #only for testing porposes
    volumes:
      - "db_volume:/var/lib/postgresql"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
  
networks:
  backend:
    name: backend
    driver: bridge

volumes:
  db_volume:
