version: "3"
services:
  auth:
    container_name: auth
    env_file: 
    - .env
    - .env.profile-db
    build:
      context: .
      dockerfile: Dockerfile
    image: auth
    volumes:
    - ".:/app" #only for developement
    - "/app/node_modules"
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "3003:3000" #only for testing porposes
    depends_on:
      - profile_db
  
  profile_db:
    container_name: profile_db
    env_file: 
    - .env
    - .env.profile-db
    build:
      context: ../../database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432" #only for testing porposes
    volumes:
      - "db_volume:/var/lib/postgresql"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
  
networks:
  backend:
    name: backend
    driver: bridge

volumes:
  db_volume:
