version:  '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context:  .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # environment:
    #   - PORT=3000
    volumes:
      - ./frontend:/shared

  backend:
    container_name: backend
    build:
      context:  .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    # environment:
    #   - PORT=3000
    volumes:
      - ./backend:/shared

  test:
    container_name: test
    build:
      context:  .
      dockerfile: Dockerfile
    volumes:
      - ./test:/shared
