#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

	CREATE USER $POSTGRES_USER_AUTH WITH PASSWORD '$POSTGRES_PASSWORD_AUTH';
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER_AUTH;
	GRANT ALL ON SCHEMA public TO $POSTGRES_USER_AUTH;
EOSQL
