version: "3"
services:
  gateway:
    container_name: gateway
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    image: gateway
    volumes:
    - ".:/app" #only for developement
    - "/app/node_modules"
    restart: unless-stopped
    ports:
      - "3000:3000"