version: "3"
services:
  game:
    container_name: game
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    image: game
    volumes:
    - ".:/app" #only for developement
    - "/app/node_modules"
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "3006:3000" #only for testing porposes
    depends_on:
      - postgres
  
  postgres:
    container_name: postgres
    env_file: .env
    build:
      context: ../backend/database
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "db_volume:/var/lib/postgresql"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
  
networks:
  backend:
    name: backend
    driver: bridge

volumes:
  db_volume:
