#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER $POSTGRES_USER_AUTH WITH PASSWORD '$POSTGRES_PASSWORD_AUTH';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER_AUTH;
    GRANT ALL ON SCHEMA public TO $POSTGRES_USER_AUTH;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER_AUTH" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE TABLE IF NOT EXISTS customer (
    user_id serial PRIMARY KEY,
    email VARCHAR ( 128 ) UNIQUE NOT NULL,
    password VARCHAR ( 50 ) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dish (
    food VARCHAR ( 128 ) PRIMARY KEY UNIQUE NOT NULL,
    quantity INTEGER NOT NULL,
    CONSTRAINT quantity CHECK (quantity >= 0)
    );

    INSERT INTO dish
    VALUES('pizza' , 4);
EOSQL